/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/Components/**/*.{js,ts,jsx,tsx}",
    "./src/PageComponents/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Essential base classes
    "absolute",
    "relative",
    "fixed",
    "static",
    "block",
    "flex",
    "grid",
    "hidden",
    "inline",
    "w-full",
    "h-full",
    "h-screen",
    "w-screen",
    "w-fit",
    "h-fit",
    "w-content",
    "text-center",
    "text-left",
    "text-right",
    "cursor-pointer",
    "overflow-y-scroll",
    "no-scrollbar",
    "flex-wrap",
    "rounded",
    "rounded-full",
    "rounded-sm",
    "rounded-lg",
    "border",
    "border-2",
    "shadow",
    "opacity-20",
    "bg-opacity-20",
    "bg-opacity-70",
    "border-opacity-10",
    "border-opacity-20",
    "transition-opacity",
    "transition-transform",
    "duration-700",
    "ease-in-out",
    "space-x-3",
    "space-y-4",
    "space-y-8",
    "list-disc",
    "z-10",
    "z-40",
    "items-center",
    "justify-center",
    "mx-auto",
    "my-auto",

    // Colors
    "bg-green-500",
    "bg-green-600",
    "text-green-600",
    "border-green-500",
    "border-green-600",
    "border-green-950",
    "text-white",
    "bg-white",
    "fill-white",
    "bg-[#050f05]",
    "bg-[#061c03]",
    "bg-[#091a09]",
    "bg-[#21551b]",
    "text-[#878686]",
    "text-[#878c8d]",
    "text-[#a7aaa7]",
    "text-[#cdcbcb]",
    "text-[#f0f5f0]",
    "fill-[#21551b]",
    "stroke-[#21551b]",
    "bg-gradient-to-r",
    "from-[#061c03]",
    "from-[#4c8e43]",

    // Text sizes
    "text-xs",
    "text-sm",
    "text-lg",
    "text-xl",
    "text-[0.5rem]",
    "text-[0.75rem]",
    "text-[0.825rem]",
    "text-[1rem]",
    "text-[2rem]",
    "text-[2.25rem]",
    "text-[2.5rem]",
    "text-[3rem]",
    "text-[4.5rem]",

    // Responsive text sizes
    "xs:text-[1.25rem]",
    "xs:text-[2rem]",
    "xs:text-[2.25rem]",
    "sm:text-[1rem]",
    "sm:text-[2rem]",
    "sm:text-[2.25rem]",
    "md:text-[2.5rem]",
    "md:text-[3rem]",
    "lg:text-[3rem]",
    "lg:text-[4.5rem]",

    // Spacing
    "p-2",
    "p-3",
    "p-4",
    "p-10",
    "px-4",
    "px-8",
    "py-1",
    "py-2",
    "py-10",
    "m-4",
    "mx-2",
    "mx-4",
    "my-2",
    "my-4",
    "mb-1",
    "mb-2",
    "mb-4",
    "mb-6",
    "ml-1",
    "ml-2",
    "ml-4",
    "mr-2",
    "mt-1",
    "mt-3",
    "mt-4",
    "mt-12",
    "pb-1",
    "pb-4",
    "pb-12",
    "pl-1",
    "pt-6",
    "pt-12",

    // Arbitrary spacing values
    "h-[1.5rem]",
    "h-[2rem]",
    "h-[2.5rem]",
    "h-[3.5rem]",
    "h-[4rem]",
    "h-[9.5rem]",
    "h-[100%]",
    "w-[1.5rem]",
    "w-[3.5rem]",
    "w-[4rem]",
    "w-[4.5rem]",
    "w-[14.5rem]",
    "w-[15rem]",
    "w-[17rem]",
    "w-[18rem]",
    "w-[20rem]",
    "w-[22rem]",
    "w-[24rem]",
    "max-w-[5rem]",
    "max-w-[20.5rem]",
    "max-w-[32rem]",
    "max-w-[50rem]",
    "max-w-[60rem]",
    "max-w-[75rem]",
    "min-h-[6rem]",
    "min-w-[6rem]",
    "min-w-[9rem]",
    "min-w-[19.15rem]",
    "my-[1.5rem]",
    "mb-[8rem]",
    "pb-[4rem]",
    "pb-[5rem]",
    "pt-[0.2rem]",
    "ml-[-0.5rem]",
    "ml-[0.2rem]",
    "ml-[0.3rem]",
    "mt-[-0.5rem]",

    // Positioning
    "top-0",
    "top-2",
    "top-12",
    "bottom-0",
    "bottom-4",
    "left-0",
    "left-6",
    "left-[0.5rem]",
    "left-[2.5rem]",
    "left-[22.5rem]",
    "right-[3rem]",
    "translate-x-[1.9rem]",

    // Responsive classes
    "xs:block",
    "xs:hidden",
    "xs:mx-auto",
    "xs:my-1",
    "xs:my-8",
    "xs:right-8",
    "xs:top-12",
    "xs:ml-[2.5rem]",
    "xs:mr-[2rem]",
    "xs:mt-[35%]",
    "xs:pl-0",
    "xs:pt-[6rem]",
    "sm:block",
    "sm:hidden",
    "sm:right-12",
    "sm:top-12",
    "sm:my-3",
    "sm:my-6",
    "sm:ml-[12rem]",
    "sm:mr-[4rem]",
    "sm:flex-none",
    "sm:space-x-0",
    "sm:p-2",
    "sm:p-6",
    "sm:pt-[6rem]",
    "md:block",
    "md:hidden",
    "md:my-10",
    "md:mt-[10%]",
    "md:min-w-[4rem]",
    "md:flex-none",
    "md:space-x-0",
    "md:p-4",
    "md:p-8",
    "md:pl-0",
    "lg:flex",
    "lg:min-w-[16rem]",
    "lg:space-x-8",
    "lg:p-2",
    "xl:block",
    "xl:hidden",

    // Hover states
    "hover:text-[#b1afaf]",
    "hover:text-[#cdcbcb]",
    "hover:text-white",
    "hover:brightness-90",

    // Additional utility classes
    "line-through",
    "max-h-screen",
  ],
  theme: {
    screens: {
      xs: "200px",
      // => @media (min-width: 200px { ... })
      sm: "576px",
      // => @media (min-width: 576px) { ... }
      md: "769px",
      // => @media (min-width: 769px) { ... }
      lg: "992px",
      // => @media (min-width: 992px) { ... }
      xl: "1200px",
      // => @media (min-width: 1200px) { ... }
    },
    backgroundImage: {
      "fern-image": "url('/src/Images/fernHomepage.png')",
      "footer-texture": "url('/img/footer-texture.png')",
    },
    extend: {},
  },
  plugins: [],
};
